version: "3.9"

services:
  app:
    build: .
    container_name: gps-bracelet-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./src/data:/app/src/data
    networks:
      - webnet

  nginx:
    image: nginx:stable-alpine
    container_name: gps-bracelet-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - webnet

  certbot:
    image: certbot/certbot
    container_name: gps-blinko-certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'while :; do sleep 12h & wait $${!}; certbot renew; done'"
    networks:
      - webnet

networks:
  webnet:
